# See https://docs.travis-ci.com/user/languages/php/
language: php

# Versions to test against.
php:
 - 7.1
 - 7.2
 - 7.3
 - 7.4

before_script:
 - composer install

# See https://docs.travis-ci.com/user/languages/php/#Default-Build-Script
script: vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text

# See https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
     - anthwhyte@gmail.com
     - drchuck@learnxp.com
    on_success: change
    on_failure: always
